apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.global.namePrefix }}-apiproxy-configmap
data:
  nginx.conf: |
    {{- tpl ($.Files.Get "files/nginx.conf") . | nindent 4 }}