apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "snippet.apiproxy.annotations" . | nindent 2 }}
  {{- include "snippet.apiproxy.labels" . | nindent 2 }}
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.global.namePrefix }}-apiproxy-configmap
data:
  nginx.conf: |
    {{- tpl ($.Files.Get "files/nginx.conf") . | nindent 4 }}