apiVersion: v1
kind: Service
metadata:
  {{- include "snippet.apiproxy.annotations" . | nindent 2 }}
  {{- include "snippet.apiproxy.labels" . | nindent 2 }}
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.global.namePrefix }}-apiproxy-svc
spec:
  selector:
    {{- toYaml .Values.apiproxy.selectorLabels | nindent 4 }}
  clusterIP: None
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP