global:
  namePrefix: bu-project
  annotations:
    oncallPager: 800-555-1212
  labels:
    app.kubernetes.io/managed-by: Helm

apiproxy:
  labels:
    app: apiproxy
  selectorLabels:
    app: apiproxy
  image: registry.example.com/project/apiproxy
  imageTag: "1.0"
  imagePullPolicy: IfNotPresent

webfront:
  labels:
    app: webfront
  selectorLabels:
    app: webfront
  image: registry.example.com/project/webfront
  imagePullPolicy: IfNotPresent
