---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aigc
  name: oneapi-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oneapi
  template:
    metadata:
      labels:
        app: oneapi
    spec:
      volumes:
        - name: oneapi-data-volume
          persistentVolumeClaim:
            claimName: oneapi-data-pvc
      containers:
        - name: oneapi
          image: justsong/one-api:v0.6.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 250m
              memory: 500Mi
          volumeMounts:
            - name: oneapi-data-volume
              mountPath: "/data"
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: aliyun_logs_aigc-stdout
              value: stdout
---
apiVersion: v1
kind: Service
metadata:
  namespace: aigc
  name: oneapi-svc
spec:
  selector:
    app: oneapi
  clusterIP: None
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: aigc
  name: oneapi-ingress
  annotations:
    alb.ingress.kubernetes.io/order: "996"
spec:
  ingressClassName: alb
  tls:
    - hosts:
        - aigc.example.com
  rules:
    - host: aigc.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oneapi-svc
                port:
                  number: 3000
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: aigc
  name: oneapi-data-pvc
spec:
  selector:
    matchLabels:
      alicloud-pvname: oneapi-data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oneapi-data-pv
  labels:
    alicloud-pvname: oneapi-data-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: oneapi-data-pv
    volumeAttributes:
      server: "857abc857a-bc85.cn-hangzhou.nas.aliyuncs.com"
      path: "/oneapi-data"
  mountOptions:
    - nolock,tcp,noresvport
    - vers=3
