apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.global.namePrefix }}-dockerregistry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Files.Get "files/dockerconfigjson.encrypted" | b64enc }}
