apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.global.annotations }}
  annotations:
  {{- toYaml .Values.global.annotations | nindent 4 }}
  {{- end }}
  {{- if .Values.global.labels }}
  labels:
  {{- toYaml .Values.global.labels | nindent 4 }}
  {{- end }}
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.global.namePrefix }}-dockerregistry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Files.Get "files/dockerconfigjson.encrypted" | b64enc }}
