global:
  namespace: bu-project-dev

apiproxy:
  replicas: 1
  cpu: "125m"
  memory: "256Mi"
  host: web.dev.example.com
  apiHost: api.dev.example.com

webfront:
  labels:
    app.kubernetes.io/component: server
  replicas: 1
  imageTag: "dev-2024.09.05.0923"
  cpu: "250m"
  memory: "512Mi"
  host: web.dev.example.com
  extraEnv:
    - name: APP_CONFIG
      value: dev
