global:
  namespace: bu-project-uat

apiproxy:
  replicas: 1
  cpu: "250m"
  memory: "512Mi"
  host: web.uat.example.com

webfront:
  annotations:
    app.kubernetes.io/name: webfront 
  replicas: 1
  imageTag: "uat-2024.09.05.1805"
  cpu: "500m"
  memory: "1Gi"
  host: web.uat.example.com
  extraEnv:
    - name: APP_CONFIG
      value: uat
