---
# Source: apps-overlays/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:
    oncallPager: 800-555-1212
  labels:
    app.kubernetes.io/managed-by: Manual
  namespace: bu-project-uat
  name: bu-project-dockerregistry-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.example.com": {
          "auth": "dXNlcm5hbWU6cGFzc3dvcmQ="
        }
      }
    }
