apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
            - name: manager
              resources:
                requests:
                  cpu: 250m
                  memory: 500Mi
                limits:
                  cpu: 250m
                  memory: 500Mi
              env:
              - name: aliyun_logs_flux-system-stdout
                value: stdout
    target:
      kind: Deployment
      name: "(source-controller|kustomize-controller|notification-controller)"
