---
apiVersion: v1
kind: Secret
metadata:
  namespace: bu-project-uat
  name: bu-project-dockerregistry-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.example.com": {
          "auth": "dXNlcm5hbWU6cGFzc3dvcmQ="
        }
      }
    }
