---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: bu-project-dev
namePrefix: bu-project-

configMapGenerator:
  - name: apiproxy-configmap
    files:
      - files/nginx.conf
    options:
      disableNameSuffixHash: true

images:
  - name: registry.example.com/project/webfront
    newTag: dev-2024.09.05.0923

replicas:
- name: apiproxy-deployment
  count: 1
- name: webfront-deployment
  count: 1

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: webfront-deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: 
          name: APP_CONFIG
          value: dev