---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app: webfront
    includeSelectors: true
    includeTemplates: true
  - pairs:
      app.kubernetes.io/component: server
    includeSelectors: false
    includeTemplates: true