---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps/webfront
  - apps/apiproxy
 
commonAnnotations:
  app.kubernetes.io/managed-by: Kustomization

replicas:
- name: apiproxy-deployment
  count: 1
- name: webfront-deployment
  count: 2

patches:
  - path: patches/deployment.yaml
    target:
      kind: Deployment

secretGenerator:
  - name: dockerregistry-secret
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=files/dockerconfigjson.encrypted
    options:
      disableNameSuffixHash: true