apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- include "snippet.webfront.annotations" . | nindent 2 }}
  {{- include "snippet.webfront.labels" $ | nindent 2 }}
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.global.namePrefix }}-webfront-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.webfront.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.namePrefix }}-webfront-svc
                port:
                  number: 8080
