apiVersion: v1
kind: Service
metadata:
  {{- include "snippet.webfront.annotations" . | nindent 2 }}
  {{- include "snippet.webfront.labels" . | nindent 2 }}
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.global.namePrefix }}-webfront-svc
spec:
  selector:
    {{- toYaml .Values.webfront.selectorLabels | nindent 4 }}
  clusterIP: None
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP